### ISSUE TITLE
CMake Error at third_party/cmake/vpux_elf.cmake:23 (add_subdirectory):   add_subdirectory given source "vpux_elf/vpux_elf" which is not an existing   directory. Call Stack (most recent call first):   third_party/CMakeLists.txt:7 (include)

### ISSUE THREAD

**Issue by bhardwaj-nakul** [intel/linux-npu-driver#16]
Not able to install linux-npu-driver for MTL device on Ubuntu22.04
Followed these instructions : 
```
sudo apt update
sudo apt install -y build-essential git git-lfs cmake libudev-dev libboost-all-dev
cd linux-npu-driver
cmake -B build -S .
cmake --build build --parallel $(nproc)
```

But getting this error : 

![image](https://github.com/intel/linux-npu-driver/assets/84007248/d269e7e1-d3f5-4542-afba-e3d8d8e757a9)

Can somebody help identify the issue here ?

**Comment by jwludzik** [comment]
Hi, please, first download all git submodule by calling:
```
git submodule update --init --recursive
```

And then try to compile the driver

**Comment by bhardwaj-nakul** [comment]
Thank you! This resolved the issue.
