### ISSUE TITLE
Unable to run the test 

### ISSUE THREAD

**Issue by pthorali** [intel/linux-npu-driver#47]
Hi Team, 
I am trying to install NPU to Meteor Lake machine, I followed all the steps given in the (https://github.com/intel/linux-npu-driver/blob/main/docs/overview.md) and I did not face any issue during the build, but when I try to test the application, it gives me the below error. Could you please guide me on how to proceed?

![image](https://github.com/user-attachments/assets/3f53d75f-f6ee-4d4e-997d-2f2743a6f999)

Thank you,
Preethi Raksha

**Comment by mateusztabaka** [comment]
hi, can you send me the output of following commands:
`uname -r`
`modinfo intel_vpu`
`lsmod | grep intel_vpu`
`ls -l /dev/accel/accel0`
`strace vpu-umd-test`
?

**Comment by pthorali** [comment]
1. root@mtl-nuc-14-1-1:~/linux-npu-driver# uname -r 
6.8.0-31-generic

2. root@mtl-nuc-14-1-1:~/linux-npu-driver# lsmod | grep intel_vpu
intel_vpu             245760  0

3. root@mtl-nuc-14-1-1:~/linux-npu-driver# ls -l /dev/accel/accel0
ls: cannot access '/dev/accel/accel0': No such file or directory

4. [strace_output.txt](https://github.com/user-attachments/files/16949950/strace_output.txt)

5. In below screenshot

![image](https://github.com/user-attachments/assets/ab67f2d9-26a8-4094-98bc-8716d1f72fc2)

**Comment by pthorali** [comment]
Thank you for help. 
We are trying to identify why NPU is not getting detected. Closing the issue.
