### ISSUE TITLE
The system cannot recognize NPU

### ISSUE THREAD

**Issue by RyanL00** [intel/linux-npu-driver#54]
### Environment
OS:  Ubuntu 22.04.1
Kernel: 6.8.0-45-generic
CPU: Intel(R) Core(TM) Ultra 5 135H

### Issue
According to [https://github.com/intel/linux-npu-driver/releases/tag/v1.8.0](url) Installing the NPU driver,
when executing `ls /dev/accel/accel0`, it was found that there was no accel in/dev. 
`lspci | grep -i npu`  without output.

![企业微信截图_17286313712796](https://github.com/user-attachments/assets/ca6089e0-90a3-45a8-92cc-a5ee86a3cb60)

**Comment by jwludzik** [comment]
Have you reboot the machine after installing driver? Can you check is intel_vpu kernel module successfully load in your system -
> https://github.com/intel/linux-npu-driver/blob/main/docs/overview.md#kernel-module-driver ?

**Comment by RyanL00** [comment]
I have rebooted the machine, but it did not work. It was still found that there was no accel in /dev.
`modinfo intel_vpu` `lsmod | grep intel_vpu` `dmesg | tail -n 20`
output below:
![企业微信截图_17287124185552](https://github.com/user-attachments/assets/1ba8d9ab-c40e-4e3a-9a19-c6ef015db8f8)
![企业微信截图_17287124637824](https://github.com/user-attachments/assets/a6a51060-c191-437b-8fe5-8bc181fac1e4)

**Comment by jwludzik** [comment]
Sorry for late replay. Can you check the `dmesg | grep intel_vpu` and `lspci -d 8086:7d1d` commands and send output from them?

**Comment by RyanL00** [comment]
I've tried rebooting the machine or reloading the device.
`dmesg | grep intel_vpu` and `lspci -d 8086:7d1d` without output.

yeah, it is the same issue [ openvinotoolkit/openvino#27002 ](url)

**Comment by jlawryno** [comment]
You may have NPU disabled in BIOS. Please provide full output form `lspci -vvv` and check if NPU is enabled in advanced BIOS settings. If you cannot find NPU option in BIOS you may try resetting the BIOS settings to the default.

**Comment by RyanL00** [comment]
> You may have NPU disabled in BIOS. Please provide full output form `lspci -vvv` and check if NPU is enabled in advanced BIOS settings. If you cannot find NPU option in BIOS you may try resetting the BIOS settings to the default.

Thanks, NPU is disabled in the BIOS, change it to enabled and the NPU will be recognized correctly.
